### ISSUE TITLE
Scout searchable trait only booted once

### ISSUE THREAD

**Issue by matthew-inamdar** [babenkoivan/scout-elasticsearch-driver#120]
https://github.com/babenkoivan/scout-elasticsearch-driver/blob/6214ac2dfdb68f5faa022589404e921c3dd3323f/src/Searchable.php#L27-L36

Is there a particular reason why this trait only boots the Scout trait method once?

It was causing an issue when unit testing, as it needed to be booted for each test case but was only booting once.

I've overridden the method for now to always boot the Scout trait method, but conscious about this potentially breaking something?

Thanks,
Matt

**Comment by babenkoivan** [comment]
Hi @matthew-inamdar,

there was an issue, when a model uses searchable trait from the package it was booted twice, because  searchable trait from the package uses searchable trait from Scout. Because of that, model observers were registered twice, that was causing errors when indexing / deleting data. 

I had this issue with Scout 3.0 and I'm not sure, that we still have it in 4.0 - 5.0.
In your case, if you don't get any errors from Elastic, you are safe.

**Comment by matthew-inamdar** [comment]
Cheers @babenkoivan 

I've had no issues - so happy for this to be closed.

I'll reopen if I come across any.
