### ISSUE TITLE
Diacritic insensitive ?

### ISSUE THREAD

**Issue by kevindesousa** [babenkoivan/scout-elasticsearch-driver#167]
Hello,

How enable a research with diacritic insensitive ?

For exemple, the record is  `élastic`, and my search is `elastic`

**Comment by iget-esoares** [comment]
Hi @kevindesousa. This channel is for bug or feature requests related to this package.

Since your question is about Elasticsearch mapping, I'm closing this issue and suggest you creating on question at https://stackoverflow.com/

**Tip:** Search for `asciifolding` filter and how to add it to your index analyzer.
