### ISSUE TITLE
Authenticating

### ISSUE THREAD

**Issue by louiscoetzee** [babenkoivan/scout-elasticsearch-driver#170]
good day, I want to use this library with scout to index and search text, I've signed up for elasticsearch cloud but I am not sure how to configure this to send a username and password to the hosted api. please help. I don't see anything in the readme.

**Comment by louiscoetzee** [comment]
elasticsearch' => [
'index' => env('ELASTICSEARCH_INDEX', 'laravel'),
'config' => [
'hosts' => [
'https://myusername:mypassword@xxxxxxxxxxxxxx.ap-southeast-1.aws.found.io:9243/'
],
],
],

**Comment by iget-esoares** [comment]
The `config` key will use the config pattern defined [here](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_configuration.html#_extended_host_configuration)

For default localhost connections this is enough:

```
'config' => [
  'hosts' => [
    'localhost:9200'
  ]
];
```

If you want to define an password (and more), you can do:

```
'config' => [
  'hosts' => [
        'host' => 'foo.com',
        'port' => '9200',
        'scheme' => 'https',
        'user' => 'username',
        'pass' => 'password!#$?*abc'
    ],
];
```

Closing this issue since it's just a help question. Feel free to open a new one if you find any bug or feature request.

**Comment by vpillinger** [comment]
The above answer has an error. You need to to wrap the host information in one more [] in order to pass the entire thing as a single object.

Like so:
```
'config' => [
  'hosts' => [[
        'host' => 'foo.com',
        'port' => '9200',
        'scheme' => 'https',
        'user' => 'username',
        'pass' => 'password!#$?*abc'
   ] ],
];
```
