### ISSUE TITLE
Update versión to 9

### ISSUE THREAD

**Issue by yashiroiori** [babenkoivan/scout-elasticsearch-driver#173]
Hi.
In my composer have a versión 3.8, after composer update change to version 3.9, but get error "Method Illuminate\Support\Collection::load does not exist" using "with()"
Example works in 3.8, not in 3.9:
```code
Metric::search('*')->with('uomBase')->whereExists('parent_id')->orderBy('status','desc')->orderby('name')->get()
```

**Comment by hubertnnn** [comment]
You have to update Laravel.
`Collection::load()` was added quite recently (dont remember exact version number)

**Comment by iget-esoares** [comment]
Looks like composer version constraints should be updated...

**Comment by babenkoivan** [comment]
@yashiroiori says that it worked in `3.8`, but it doesn't work in `3.9` anymore, which is weird, cause relation loading wasn't changed in `3.9`. Maybe you need to update your composer dependencies and make sure, that basic Laravel dependencies are properly installed.

**Comment by jblotus** [comment]
Having similar issues attempting to upgrade to laravel 5.8 and scout 7 

This could be related:
https://github.com/teamtnt/laravel-scout-tntsearch-driver/issues/215

https://github.com/laravel/scout/issues/339

**Comment by SouD** [comment]
I ran into this today, in our case it was because of how the `\Illuminate\Database\Eloquent\Collection::map` method works. When the search engine returned IDs that for some reason was no longer stored in our primary DB, some results would be null and not filtered out properly. This causes the `map` method to return a base collection that does not have the `load` method. :<

**Comment by babenkoivan** [comment]
@SouD the issue isn't clear to me, when ids from ES are returned, the engine makes a query to db and then filters out empty results. Also, having inconsistent data in database and ES is already an issue.

**Comment by SouD** [comment]
@babenkoivan Yeah some other dev went in and deleted rows from our DB, that's what caused the inconsistencies. My issue seems to be cause because `ElasticEngine::map` calls the collection `map` method before it calls `filter`, which causes collection `map` to return a base collection.

This is what my collection looked like when dumping the `map` (ElasticEngine.php, line 297) output, before filter has run.
```
\Illuminate\Support\Collection {#740 ▼
  #items: array:3 [▼
    0 => null
    1 => Advert {#739 ▶}
    2 => Advert {#738 ▶}
  ]
}
```
As you can see the map method has already converted the collection to a base one instead of an eloquent collection.

**Comment by yashiroiori** [comment]
Solved

**Comment by Reached** [comment]
I just experienced this issue as well, however only in my production environment (Linux Ubuntu 18.04, Elasticsearch 6.8) and not on my Mac.

The "solution" for me was to downgrade to version 3.8 of this package (remember to downgrade to Scout 4.*).

The issue seems to be only happening in certain environments...
