### ISSUE TITLE
issue with method 'hasCast' when model extends 'IndexConfigurator' instead 'Model

### ISSUE THREAD

**Issue by abkrim** [babenkoivan/scout-elasticsearch-driver#189]
Hi. 

I use a package `dyrynda/laravel-model-uuid` for use binaries uuids type 4.

When extend my class 👍 

```php
use ScoutElastic\IndexConfigurator;
use ScoutElastic\Migratable;
use Dyrynda\Database\Support\GeneratesUuid;


class Advert extends IndexConfigurator
{
    use GeneratesUuid;
    use Migratable;

   protected $casts = ['uuid' => 'uuid'];
...
```

But this code get a issue with I need implement method `hasCast`. This is a Abstract Method of GeneratesUuid

```php
/**
     * Determine whether an attribute should be cast to a native type.
     *
     * @param  string  $key
     * @param  array|string|null  $types
     * @return bool
     */
    abstract public function hasCast($key, $types = null);
```

But I'm lost about this and what can I do to correct the problem. I only know that if extend of Model work perfectly.

Apreciate some ideas.

**Comment by iget-esoares** [comment]
Hi @abkrim. 

This probably happens because you are trying to use the `GeneratesUuid` trait on your `IndexConfigurator`, but you actually need to use it on your Model instead.

The `IndexConfigurator` is only responsible for configuring your index on Elasticsearch.

I'm closing this issue since it isn't a bug or feature request. For questions please use [Stack Overflow](https://stackoverflow.com.br).
