### ISSUE TITLE
Highlight in json respons

### ISSUE THREAD

**Issue by medspec** [babenkoivan/scout-elasticsearch-driver#190]
Hi, 

in my controller i return 

return Customer::search($term)->get();

But what is the best way to add the Highlight to the returned json?

**Comment by iget-esoares** [comment]
Hi @medspec, this looks like a help question instead of an actual issue.

Please take a look at the [Search Rules section of README.md](https://github.com/babenkoivan/scout-elasticsearch-driver/blob/master/README.md). 

If you find any bugs or have any feature requests, feel free to open an new issue. I'll close this issue by now.
