### ISSUE TITLE
Model Relationship not updated in index.

### ISSUE THREAD

**Issue by paligiannis** [babenkoivan/scout-elasticsearch-driver#330]
**Versions**

- scout-elastic-driver: 4.0.1
- laravel/framwork: 5.8.*
- php: 7.2
- elasticsearch: 7.3.1

**Description**

1. I have a Product.php Model and the product has multiple prices

        public function toSearchableArray()
        {
            $array = $this->toArray();

            $array['prices'] = $this->prices;

            return $array;
        }

2. Prices belong to product.
3. Correct me if wrong, but If I change the price I should get a price change in elasticsearch. Right?
4. In my controller for changing prices

           `
            $price = Price::find($request->priceID);
            $product = Product::find($price->product_id); //There is a product_id foreight key to prices table
            $product->prices()->where('id', '=', $request->priceID)
                ->update(['price' => $request->newPrice ]);
          `
5. **When I do that there is no impact in elasticsearch index. The price is not updated.** Does anyone knows how to resolve it? I didn't found any way to resolve that.

****************
Is my issue similar to #82?

**Comment by paligiannis** [comment]
I'm so dump, really :(

**Comment by iget-esoares** [comment]
The reindexing process is not triggered by relationship changes, that's the expected behavior (from Laravel Scout, not this package).

To fiz situations like this, you can use `touch()` method on your model everytime that you update some relationship:

    $product->touch();

You can also setup a `saved` event listener on your related model to force update of it relationships everytime that it's created or updated.
