### ISSUE TITLE
Expose the Elastic Client

### ISSUE THREAD

**Issue by iget-master** [babenkoivan/scout-elasticsearch-driver#76]
Hi,

I've noticed that your package defines an `scout_elastic.client` singleton, but it's undocumented.

My question is if can I rely on this singleton externally for general purpose, or if I'll need to create my own singleton (bad idea since I'll have two simultaneous clients).

If I can rely on it, I suggest that it's added to documentation.

**Comment by babenkoivan** [comment]
Hi @iget-master, I think you can use it, but this is internal package functionality, that's why it's not documented.

But if you want, you can use [Facade](https://github.com/babenkoivan/scout-elasticsearch-driver/blob/master/src/Facades/ElasticClient.php). I don't think that it will be changed in the near future.
