### ISSUE TITLE
Import does not complete

### ISSUE THREAD

**Issue by ahmadarif** [babenkoivan/scout-elasticsearch-driver#8]
I'm use `ES 5.5.2`, and import the laravel scout from existing data with no error.
But when I search with some keyword, the result is empty.
Is the import does not complete?

**Comment by babenkoivan** [comment]
Hi @ahmadarif,

Let's check if all your data imported to ES. First, find out how many records you have in your DB, then make a simple search query to ES, in order to get a number of documents in your index:

```
// use your model name instead of YourModel
YourModel::searchRaw(['query' => ['bool' => ['match_all' => []]]])['hits']['total']
```

If the numbers are the same, so you probably have a problem with configuration or search query. If they are different, we will try to find a problem with it.

**Comment by babenkoivan** [comment]
Haven't got a feedback here, so I close it.

**Comment by anbu369** [comment]
@babenkoivan  I have the same issue. imported all the records but search returns empty. I have 15802 records in my db but there are only 15762 in ES
